### ISSUE TITLE
Resistor: Use actual buttons instead of <span>s with content in ::after

### ISSUE THREAD

**Issue by FLamparski** [MightyPork/bits-ondrovo#1]
Seriously, it might break any assistive technologies because the content is not there, and Firefox sometimes has trouble toggling off the :active state on those spans.

Playing around, I found that you can apply the `.color` styles to normal buttons and they just work; and you can replace the ::after pseudo-element with normal text inside the button.

**Comment by MightyPork** [comment]
looks uglier in firefox, but i guess it's worth that sacrifice..
